app/models.py
from flask_login import UserMixin
from . import db,login_manager


class Users(UserMixin,db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String , unique = True, nullable=False)
    email = db.Column(db.String)
    password = db.Column(db.String) 
    pitches = db.relationship('Pitch', backref='owner')
    comments = db.relationship('Comment', backref='owner')
    def __repr__(self):
       return f"User('{self.username}')"

    @login_manager.user_loader
    def load_user(user):
        return Users.query.get(int(user))   
 
class Pitch(db.Model):
    __tablename__ = 'pitches'
    id= db.Column(db.Integer, primary_key = True)
    owner_id = db.Column(db.Integer, db.ForeignKey ("user.id"), nullable=False)
    description = db.Column(db.String(), index=True)
    title = db.Column(db.String())
    category = db.Column(db.String(255), nullable=False)  
    def __repr__(self):
            return f'Pitch {self.description}'  
    


class Comment(db.Model):
    __tablename__ = 'comment'
    id= db.Column(db.Integer, primary_key = True)
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    content = db.Column(db.String(255), index=True)
    def __repr__(self):
            return f'Comment {self.content}'

    

main/models.py
from flask_sqlalchemy import SQLAlchemy
from ..app import db
from . import login_manager


class Users(UserMixin,db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String , unique = True, nullable=False)
    email = db.Column(db.String)
    password = db.Column(db.String) 
    pitches = db.relationship('Pitch', backref='owner')
    comments = db.relationship('Comment', backref='owner')
    def __repr__(self):
       return f"User('{self.username}')"

    @login_manager.user_loader
    def load_user(user_id):
        return Users.query.get(int(user_id))   
# class Categories(db.Model):
#     __tablename__ = 'categories'

#     id= db.Column(db.Integer, primary_key = True)
#     # name = db.Column(db.String)
 
class Pitches(db.Model):
    id= db.Column(db.Integer, primary_key = True)
    owner_id = db.Column(db.Integer, db.ForeignKey ("user.id"), nullable=False)
    description = db.Column(db.String(), index=True)
    title = db.Column(db.String())
    category = db.Column(db.String(255), nullable=False)  
    def __repr__(self):
            return f'Pitch {self.description}'  
    # category = db.relationship(Categories, backref=db.backref("pitches"), lazy = True)


class Comment(db.Model):
    id= db.Column(db.Integer, primary_key = True)
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    content = db.Column(db.String(255), index=True)
    def __repr__(self):
            return f'Comment {self.content}'

    # comment = db.Column(db.Text)

class Votes(db.Model):
      id= db.Column(db.Integer, primary_key = True)
      up_votes = db.Column(db.Integer)
      down_votes = db.Column(db.Integer)
      def __repr__(self):
            return f'Votes{self.votes}'

app/main/forms.py
from wtforms import StringField, PasswordField, BooleanField
from flask_wtf import FlaskForm, form
from wtforms.validators import InputRequired, Email
from wtforms.widgets import TextArea

class LoginForm(FlaskForm):
    username = StringField('Username',validators=[InputRequired()])
    password = PasswordField('Password',validators=[InputRequired()])
    remember = BooleanField('Remember')
    
class RegisterForm(FlaskForm):
    
    email = StringField('Email', validators=[InputRequired(), Email()])
    username = StringField('username',validators=[InputRequired()])   
    password = PasswordField('Password',validators=[InputRequired()])
    
    
class PitchForm(FlaskForm):
    
    title = StringField('Title of pitch',validators=[InputRequired()])
    category = StringField('Category: Innovation, Business or Pickup Line',validators=[InputRequired()])
    description = StringField('Pitch',validators=[InputRequired()], widget=TextArea())
    
class CommentForm(FlaskForm):
    content = StringField('Comment')  

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

db = SQLAlchemy()
bootstrap = Bootstrap()
def create_app(config_name):
    app = Flask(__name__)
    
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from flask_wtf import FlaskForm
from .forms import LoginForm, RegisterForm, PitchForm, CommentForm
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import LoginManager, UserMixin, login_required, login_user, logout_user, current_user
from ..models import Users,Pitch,Comment
from .. import db

@main.route("/")
def index ():
    return render_template("index.html")

@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
       
        new_user = Users(username=form.username.data, email=form.email.data, password=hashed_password)
    
        db.session.add(new_user)
        db.session.commit()
        return redirect('/success')
    return render_template('signup.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('main.dashboard'))
         
        return redirect('failure')
    
  
    return render_template('login.html', form=form )

@main.route('/success')
def success():
    
    return render_template('success.html')

@main.route('/failure')
def failure():
    
    return render_template('failure.html')

@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    pitch = Pitch.query.all()
    
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(owner_id=current_user.id, content=form.content.data)
        form.content.data = ''
       
        
        db.session.add(comment)
        db.session.commit()
    return render_template('dashboard.html', name=current_user.username, pitch=pitch, form=form, content=form.content.data)

@main.route('/pitch', methods=['GET', 'POST'])
@login_required
def pitch():
    form = PitchForm()
    
    if form.validate_on_submit():
        pitch = Pitch(owner_id=current_user.id, title=form.title.data, category=form.category.data, description=form.description.data)
        form.title.data = ''
        form.category.data = ''
        form.description.data = ''
        
        db.session.add(pitch)
        db.session.commit()
    return render_template('pitch.html', form=form)

@main.route('/profile')
@login_required
def profile():
    
    pitch = Pitch.query.filter_by(id=current_user.id).all()
    
    return render_template('profile.html', name=current_user.username, email=current_user.email, password=current_user.password, pitch=pitch)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

main/views.py
from flask import render_template as render,request,redirect,url_for
from flask_wtf import FlaskForm
from .forms import LoginForm, RegisterForm, PitchForm, CommentForm
from .models import Users, Pitch, Comment
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import LoginManager, UserMixin, login_required, login_user, logout_user, current_user
from . import main
from .main import main_blueprint as main


@main.route("/")
def index ():
    return render("index.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PitchBank</title>
</head>
<body>
    
</body>
</html>

app/templates/dashboard.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{super()}}

<link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100;200;300;400;500;600;700&family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Playfair+Display+SC:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Special+Elite&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">

{% endblock %}


{% block content %}
<div class="container-fluid nav text-center">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <h3>PITCH BANK</h3>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{ url_for('main.profile')}}">
                <h3>PROFILE</h3>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{url_for('main.logout')}}">
                <h3>LOGOUT</h3>
            </a>
        </div>
    </div>

</div>

<div class="container text-center">
    <h1 class="welcome">WELCOME, {{ name }}</h1>
    <p>Pitch Bank allows you to submit pitches in various categories. You can browse the page to view posted
        pitches or submit your own.</p>
</div>

<div class="container-fluid categories">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body text-center">
                    <h4 class="card-title">BUSINESS PITCH</h4>
                    <p class="card-text">A promising business idea that will be guaranteed to take off.</p>
                    <a href="{{ url_for('main.pitch') }}" class="btn btn-primary">Submit Your Pitch</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body text-center">
                    <h4 class="card-title">INNOVATION PITCH</h4>
                    <p class="card-text">A new and exciting idea, relevant for the present times.</p>
                    <a href="{{ url_for('main.pitch') }}" class="btn btn-primary">Submit Your Pitch</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body text-center">
                    <h4 class="card-title">PICKUP LINE</h4>
                    <p class="card-text">Creative pick-up lines that will make you unforgettable!</p>
                    <a href="{{ url_for('main.pitch') }}" class="btn btn-primary">Submit Your Pitch</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <h3>BELOW ARE VARIOUS SUBMITTED PITCHES</h3>

</div>
<div class="container pitches-section">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">

            {% for p in pitch %}
            <p>TITLE: {{p.title}} </p>
            <p>CATEGORY: {{p.category}}</p>
            <p>PITCH: {{p.description}}</p>
            <p>Submitted by: {{p.owner.username}}</p>


            <form class="form-signin" method="POST" action="/dashboard">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.content) }}
                <button class="btn btn-lg btn-primary btn-block comment-btn" type="submit">Post comment</button>
            </form>
            <hr>
            {% endfor %}
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            {% for comment in comments %}
            <p> {{comment.content}}</p>

            {% endfor %}
        </div>


    </div>

</div>
{% endblock %}

app/templates/failure.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}


{% block content %}

<div class="jumbotron failure jumbotron-fluid text-center">
    <div class="container">
      <h2 class="display-4">SORRY</h2> 
      <p class="lead">Invalid password or username.</p>
      <a href="{{ url_for('main.login') }}"><button class="btn again btn-primary">Try Again</button></a>
    </div>
  </div>
{% endblock %}

app/templates/index.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}

<link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100;200;300;400;500;600;700&family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Playfair+Display+SC:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Special+Elite&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content%}

<div class="container-fluid">
    <div class="jumbotron text-center">
        <p>Welcome to</p>
        <h1 class="display-4 intro">PITCH BANK</h1>
        <p>Make your sixty seconds count!</p>

        <a href="{{ url_for('main.signup') }}"><button class="btn btn-light">Sign-up</button></a>
        <a href="{{ url_for('main.login') }}"><button type="button" class="btn btn-dark">Login</button></a>
    </div>
</div>

{% endblock %}

app/templates/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block content %}
<a href="{{ url_for('main.index') }}"><button class="btn back btn-primary">Back</button></a>
<div class="container signup text-center">

  <form class="form-signin" method="POST" action="/login">
    <h4 class="form-signin-heading">Please Login to Continue</h4>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.password) }}


    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  </form>

</div>

{% endblock%}

app/templates/pitch.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100;200;300;400;500;600;700&family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Playfair+Display+SC:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Special+Elite&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<a href="{{url_for('main.dashboard')}}"><button class="btn btn-primary home">Home</button></a>
<div class="container signup text-center">

    <form class="form-signin" method="POST" action="/pitch">
      <h4 class="form-signin-heading">Add Your Pitch Here</h4>
      {{ form.hidden_tag() }}
      {{ wtf.form_field(form.title) }}
      {{ wtf.form_field(form.category) }}
      {{ wtf.form_field(form.description) }}
  
      <button class="btn btn-lg btn-primary btn-block" type="submit">Submit Pitch</button>
    </form>

{% endblock %}

app/templates/profile.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100;200;300;400;500;600;700&family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Playfair+Display+SC:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Special+Elite&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container-fluid nav text-center">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{url_for('main.dashboard')}}">
                <h3>DASHBOARD</h3>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{ url_for('main.profile')}}">
                <h3>PROFILE</h3>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{url_for('main.logout')}}">
                <h3>LOGOUT</h3>
            </a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6">
            <h3>USER INFORMATION</h3>
            <p>USERNAME: {{ name }}</p>
            <p>USER EMAIL ADDRESS: {{ email }}</p>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-6">
            <h3>PITCHES SUBMITTED</h3>
            <div>
                {% for p in pitch %}
                <p>Title: {{p.title}} </p>
                <p>Category: {{p.category}}</p>
                <p>Content of the pitch: {{p.description}}</p>
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Sign Up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block content %}
<a href="{{ url_for('main.index') }}"><button class="btn back btn-primary">Back</button></a>
<div class="container signup text-center">
  <form class="form-signin" method="POST" action="/signup">
    <h2 class="form-signin-heading">Sign Up</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.password) }}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
  </form>
</div> 
{% endblock %}

app/templates/success.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100;200;300;400;500;600;700&family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Playfair+Display+SC:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Special+Elite&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}

<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
      <h2 class="display-4">CONGRATULATIONS!</h2> 
      <p>You have successfully created a Pitch Perfect account</p>
      <a href="{{ url_for('main.login') }}"><button class="btn btn-primary">Proceed to Login</button></a>
    </div>
  </div>
{% endblock %}